In [1]:
import pandas as pd

In [15]:
df = pd.DataFrame(data=[
    [1, "b1", 100],
    [1, "b1", 100],
    [1, "b1", 100],
    [2, "b2", 50],
    [2, "b2", 100],
])

df.columns = ['emp_id','branch_code','sales']
df

   emp_id branch_code  sales
0       1          b1    100
1       1          b1    100
2       1          b1    100
3       2          b2     50
4       2          b2    100

In [30]:
def topEmp(df):
    # Write your code here
    df_byEmployee = df.groupby('emp_id').sum('sales').reset_index()
    idx = df_byEmployee['sales'].idxmax()
    table = df_byEmployee.iloc[[idx,]].drop(columns=['sales'])
    return table

topEmp(df)

   emp_id
0       1